"""
Django settings for legitcheck project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import sys

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
LOCAL_DEV = os.environ.get("LOCAL_DEV") == "1"
RUNNING_TESTS = "test" in sys.argv

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if LOCAL_DEV or RUNNING_TESTS:
        SECRET_KEY = "django-insecure-local-development-only"
    else:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY is required")

TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_VERDICT_CHAT_ID = os.environ.get("TELEGRAM_VERDICT_CHAT_ID")
TELEGRAM_VERDICT_CHAT_15_30M_ID = os.environ.get("TELEGRAM_VERDICT_CHAT_15_30M_ID", "")
TELEGRAM_VERDICT_CHAT_1H_ID = os.environ.get("TELEGRAM_VERDICT_CHAT_1H_ID", "")
TELEGRAM_VERDICT_CHAT_2H_ID = os.environ.get("TELEGRAM_VERDICT_CHAT_2H_ID", "")
TELEGRAM_VERDICT_CHAT_3H_ID = os.environ.get("TELEGRAM_VERDICT_CHAT_3H_ID", "")
TELEGRAM_VERDICT_CHAT_12H_ID = os.environ.get("TELEGRAM_VERDICT_CHAT_12H_ID", "")
TELEGRAM_API_PROXY = os.environ.get("TELEGRAM_API_PROXY", "")
YOOKASSA_ACCOUNT_ID = os.environ.get("YOOKASSA_ACCOUNT_ID", "")
YOOKASSA_SECRET_KEY = os.environ.get("YOOKASSA_SECRET_KEY", "")
YOOKASSA_TAX_SYSTEM_CODE = os.environ.get("YOOKASSA_TAX_SYSTEM_CODE", "").strip()
YOOKASSA_RETURN_URL = os.environ.get(
    "YOOKASSA_RETURN_URL",
    f"{os.environ.get('PUBLIC_BASE_URL', 'https://legitcheck.one').rstrip('/')}/payment/success/",
)
VK_GROUP_TOKEN = os.environ.get("VK_GROUP_TOKEN", "")
VK_GROUP_ID = os.environ.get("VK_GROUP_ID", "")
VKCHAT_VAPID_PUBLIC_KEY = os.environ.get("VKCHAT_VAPID_PUBLIC_KEY", "")
VKCHAT_VAPID_PRIVATE_KEY = os.environ.get("VKCHAT_VAPID_PRIVATE_KEY", "")
VKCHAT_VAPID_CLAIM_EMAIL = os.environ.get("VKCHAT_VAPID_CLAIM_EMAIL", "admin@legitcheck.one")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1" if LOCAL_DEV else "0") == "1"

DEFAULT_ALLOWED_HOSTS = [
    '89.169.2.234',
    'legitcheck.one',
    'www.legitcheck.one',
    'checkerlegit.com',
    'www.checkerlegit.com',
    '127.0.0.1',
]
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", ",".join(DEFAULT_ALLOWED_HOSTS)).split(",")
    if host.strip()
]

if LOCAL_DEV:
    ALLOWED_HOSTS += ['localhost']

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "https://legitcheck.one,https://www.legitcheck.one,https://checkerlegit.com,https://www.checkerlegit.com",
    ).split(",")
    if origin.strip()
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = not LOCAL_DEV
SECURE_HSTS_SECONDS = 0 if LOCAL_DEV else 31536000
SESSION_COOKIE_SECURE = not LOCAL_DEV
CSRF_COOKIE_SECURE = not LOCAL_DEV

# Keep users logged in for 1 year
SESSION_COOKIE_AGE = 365 * 24 * 60 * 60  # seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = False  # сохранять только при изменении сессии

PUBLIC_BASE_URL = os.environ.get("PUBLIC_BASE_URL", "https://legitcheck.one")
if LOCAL_DEV and "PUBLIC_BASE_URL" not in os.environ:
    PUBLIC_BASE_URL = "http://127.0.0.1:8000"

STATIC_ROOT = '/srv/legitcheck/static'

# where uploaded files are stored on disk
MEDIA_ROOT = "/srv/legitcheck/media"

# URL prefix for accessing those files
MEDIA_URL = "/media/"


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'webapp',
    'pcwebapp',
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'legitcheck.host_routing_middleware.DomainRoutingMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,
        'OPTIONS': {
            'MAX_ENTRIES': 10000,
        },
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"

# Whitenoise: отдаёт статику с gzip/br сжатием и Cache-Control: max-age=1 год
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if not LOCAL_DEV
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}


ROOT_URLCONF = 'legitcheck.urls'

_TEMPLATE_LOADERS = (
    [
        ('django.template.loaders.cached.Loader', [
            'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader',
        ]),
    ]
    if not LOCAL_DEV else None
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': LOCAL_DEV,  # в prod отключаем — используем cached loader
        'OPTIONS': {
            'context_processors': [
                *(['django.template.context_processors.debug'] if LOCAL_DEV else []),
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            **({'loaders': _TEMPLATE_LOADERS} if _TEMPLATE_LOADERS else {}),
        },
    },
]

WSGI_APPLICATION = 'legitcheck.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'CONN_MAX_AGE': 60,  # переиспользовать соединение 60 сек
        'OPTIONS': {
            'timeout': 20,
            'init_command': (
                "PRAGMA journal_mode=WAL;"
                "PRAGMA synchronous=NORMAL;"
                "PRAGMA temp_store=MEMORY"
            ),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ─── Email (OTP-авторизация) ──────────────────────────────────────────────────
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "checkercheckerlegit@gmail.com")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "LegitCheck <checkercheckerlegit@gmail.com>",
)
EMAIL_TIMEOUT = 5  # быстро падаем если SMTP недоступен

# App Store Review demo access. Keep disabled unless both values are set in env.
APP_REVIEW_DEMO_EMAIL = os.environ.get("APP_REVIEW_DEMO_EMAIL", "").strip().lower()
APP_REVIEW_DEMO_PASSWORD = os.environ.get("APP_REVIEW_DEMO_PASSWORD", "")
APP_REVIEW_DEMO_BALANCE = os.environ.get("APP_REVIEW_DEMO_BALANCE", "5000")
