# Generated by Django 5.2.4 on 2026-02-08 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
        ('pcwebapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedVerdictPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='verdicts/uploads')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_verdict_photos', to='webapp.user')),
                ('verdict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_uploaded_photos', to='webapp.verdict')),
            ],
            options={
                'verbose_name': 'Загруженная фотография вердикта',
                'verbose_name_plural': 'Загруженные фотографии вердикта',
            },
        ),
    ]
