# Generated by Django 5.2.4 on 2025-07-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcwebapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('logo_url', models.URLField(max_length=500)),
                ('brand_id', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
