# Generated by Django 5.2.3 on 2026-03-07 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcwebapp', '0002_uploadedverdictphoto'),
        ('webapp', '0002_uploadedverdictphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedverdictphoto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_uploaded_verdict_photos', to='webapp.user'),
        ),
        migrations.AlterField(
            model_name='uploadedverdictphoto',
            name='verdict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pc_source_uploaded_photos', to='webapp.verdict'),
        ),
    ]
