# Generated by Django 5.2.3 on 2026-07-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcwebapp', '0003_fix_related_name_clash'),
        ('webapp', '0010_alter_verdictphoto_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['category', 'brand'], name='brand_category_name_idx'),
        ),
        migrations.AddIndex(
            model_name='logintoken',
            index=models.Index(fields=['ip_address', 'used_at', '-created_at'], name='login_ip_used_created_idx'),
        ),
        migrations.AddIndex(
            model_name='logintoken',
            index=models.Index(fields=['expires_at'], name='login_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='logintoken',
            index=models.Index(fields=['user', 'used_at'], name='login_user_used_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedverdictphoto',
            index=models.Index(fields=['user', 'verdict'], name='pcupload_user_verdict_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedverdictphoto',
            index=models.Index(fields=['user', '-created_at'], name='pcupload_user_created_idx'),
        ),
    ]
