# Generated by Django 5.2 on 2025-04-16 14:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('tgId', models.IntegerField(primary_key=True, serialize=False, verbose_name='Telegram ID')),
                ('img', models.CharField(max_length=255, verbose_name='Profile Image URL')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Username')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает оплаты'), ('COMPLETED', 'Оплачено'), ('FAILED', 'Ошибка оплаты')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='webapp.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LEGIT', 'LEGIT'), ('NO LEGIT', 'NO LEGIT')], max_length=20, verbose_name='Категория нарушения')),
                ('photo1', models.CharField(max_length=255, verbose_name='Фото 1 URL')),
                ('photo2', models.CharField(max_length=255, verbose_name='Фото 2 URL')),
                ('photo3', models.CharField(max_length=255, verbose_name='Фото 3 URL')),
                ('photo4', models.CharField(max_length=255, verbose_name='Фото 4 URL')),
                ('photo5', models.CharField(max_length=255, verbose_name='Фото 5 URL')),
                ('photo6', models.CharField(max_length=255, verbose_name='Фото 6 URL')),
                ('photo7', models.CharField(max_length=255, verbose_name='Фото 7 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='webapp.user', verbose_name='Пользователь')),
            ],
        ),
    ]
