# Generated by Django 5.2.4 on 2025-12-31 12:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('tgId', models.IntegerField(primary_key=True, serialize=False, verbose_name='Telegram ID')),
                ('img', models.CharField(max_length=255, verbose_name='Profile Image URL')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('balance', models.CharField(max_length=255, verbose_name='Баланс')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Username')),
            ],
            options={
                'verbose_name': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает оплаты'), ('COMPLETED', 'Оплачено'), ('FAILED', 'Ошибка оплаты')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('provider_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='webapp.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('inpending', 'В обработке'), ('todo', 'Требует действия'), ('fake', 'Подделка'), ('legit', 'Оригинал'), ('dont_payment', 'Не оплачено')], max_length=20, verbose_name='Категория нарушения')),
                ('category', models.CharField(choices=[('sneakers', 'Кроссовки'), ('clothes', 'Одежда'), ('bags', 'Сумки'), ('belts', 'Ремни'), ('watch', 'Часы'), ('cosmetics', 'Косметика'), ('jewerly', 'Украшения'), ('toys', 'Игрушки'), ('accsesory', 'Аксессуары'), ('others', 'Другое')], max_length=30, verbose_name='Категория вещи')),
                ('brand', models.CharField(max_length=40, verbose_name='Бренд')),
                ('item_model', models.CharField(max_length=40, verbose_name='Модель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment', models.CharField(max_length=9999)),
                ('comment_from_user', models.CharField(max_length=9999, verbose_name='Комментарий пользователя')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('speed', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('with_reason', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='webapp.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вердикты',
                'verbose_name_plural': 'Вердикты',
            },
        ),
        migrations.CreateModel(
            name='VerdictPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='verdicts/photos', verbose_name='Фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('verdict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='webapp.verdict', verbose_name='Вердикт')),
            ],
            options={
                'verbose_name': 'Фотография вердикта',
                'verbose_name_plural': 'Фотографии вердикта',
            },
        ),
    ]
