# Generated by Django 5.2 on 2025-04-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='verdict',
            options={'verbose_name': 'Вердикты', 'verbose_name_plural': 'Вердикты'},
        ),
        migrations.AlterField(
            model_name='verdict',
            name='photo1',
            field=models.ImageField(upload_to='verdicts/photos', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='photo2',
            field=models.ImageField(upload_to='verdicts/photos', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='photo3',
            field=models.ImageField(upload_to='verdicts/photos', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='photo4',
            field=models.ImageField(upload_to='verdicts/photos', verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='photo5',
            field=models.ImageField(upload_to='verdicts/photos', verbose_name='Фото 5'),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='photo6',
            field=models.ImageField(upload_to='verdicts/photos', verbose_name='Фото 6'),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='photo7',
            field=models.ImageField(upload_to='verdicts/photos', verbose_name='Фото 7'),
        ),
    ]
