# Generated by Django 5.2 on 2025-04-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_payment_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verdict',
            name='comment',
            field=models.CharField(default=1, max_length=9999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verdict',
            name='category',
            field=models.CharField(choices=[('LEGIT', 'LEGIT'), ('FAKE', 'FAKE')], max_length=20, verbose_name='Категория нарушения'),
        ),
    ]
