# Generated by Django 5.2.4 on 2026-03-11 19:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_uploadedverdictphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
