# Generated by Django 5.2 on 2025-05-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verdict',
            name='category',
            field=models.CharField(choices=[('В обработке', 'inpending'), ('Требует действия', 'todo'), ('Подделка', 'fake'), ('Оригинал', 'legit'), ('Не оплачено', 'dont_payment')], max_length=20, verbose_name='Категория нарушения'),
        ),
    ]
