# Generated by Django 5.2.3 on 2026-04-11 00:00

from django.db import migrations, models


DEFAULT_ITEMS = (
    {
        "position": 1,
        "title": "Balenciaga Track",
        "subtitle": "White Orange",
        "fallback_image": "balenciaga_track.png",
        "views_count": 231,
        "legit_percent": 43,
        "fake_percent": 57,
    },
    {
        "position": 2,
        "title": "Balenciaga Track",
        "subtitle": "White Orange",
        "fallback_image": "balenciaga_track.png",
        "views_count": 231,
        "legit_percent": 43,
        "fake_percent": 57,
    },
    {
        "position": 3,
        "title": "Balenciaga Track",
        "subtitle": "White Orange",
        "fallback_image": "balenciaga_track.png",
        "views_count": 231,
        "legit_percent": 43,
        "fake_percent": 57,
    },
    {
        "position": 4,
        "title": "Balenciaga Track",
        "subtitle": "White Orange",
        "fallback_image": "balenciaga_track.png",
        "views_count": 231,
        "legit_percent": 43,
        "fake_percent": 57,
    },
    {
        "position": 5,
        "title": "Balenciaga Track",
        "subtitle": "White Orange",
        "fallback_image": "balenciaga_track.png",
        "views_count": 231,
        "legit_percent": 43,
        "fake_percent": 57,
    },
)


def create_default_popular_items(apps, schema_editor):
    HomePagePopularItem = apps.get_model("webapp", "HomePagePopularItem")
    for item_data in DEFAULT_ITEMS:
        HomePagePopularItem.objects.get_or_create(position=item_data["position"], defaults=item_data)


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0004_emailotptoken_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePagePopularItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveSmallIntegerField(help_text="Допустимы значения от 1 до 5.", unique=True, verbose_name="Позиция")),
                ("title", models.CharField(max_length=255, verbose_name="Название модели")),
                ("subtitle", models.CharField(blank=True, help_text="Например: White Orange", max_length=255, verbose_name="Подзаголовок")),
                ("image", models.ImageField(blank=True, null=True, upload_to="homepage/popular_models/", verbose_name="Изображение")),
                ("fallback_image", models.CharField(default="balenciaga_track.png", help_text="Файл из каталога static/, используется если изображение не загружено.", max_length=255, verbose_name="Статическое изображение")),
                ("views_count", models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")),
                ("legit_percent", models.PositiveSmallIntegerField(default=0, verbose_name="Процент оригинала")),
                ("fake_percent", models.PositiveSmallIntegerField(default=0, verbose_name="Процент подделок")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
            ],
            options={
                "verbose_name": "Популярная модель главной страницы",
                "verbose_name_plural": "Топ-5 моделей главной страницы",
                "ordering": ["position"],
            },
        ),
        migrations.AddConstraint(
            model_name="homepagepopularitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1), ("position__lte", 5)),
                name="webapp_homepagepopularitem_position_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="homepagepopularitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("legit_percent__gte", 0), ("legit_percent__lte", 100)),
                name="webapp_homepagepopularitem_legit_percent_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="homepagepopularitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("fake_percent__gte", 0), ("fake_percent__lte", 100)),
                name="webapp_homepagepopularitem_fake_percent_range",
            ),
        ),
        migrations.RunPython(create_default_popular_items, migrations.RunPython.noop),
    ]
