# Generated by Django 5.2 on 2025-05-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_verdict_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='verdict',
            name='code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
