# Generated by Django 5.2 on 2025-05-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_verdict_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verdict',
            name='category',
            field=models.CharField(choices=[('inpending', 'В обработке'), ('todo', 'Требует действия'), ('fake', 'Подделка'), ('legit', 'Оригинал'), ('dont_payment', 'Не оплачено')], max_length=20, verbose_name='Категория нарушения'),
        ),
    ]
