# Generated by Django 5.2.3 on 2026-06-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_user_free_check_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='verdict',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='verdict',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('user', 'idempotency_key'), name='unique_verdict_idempotency_key_per_user'),
        ),
    ]
