# Generated by Django 5.2 on 2025-05-13 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_verdict_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verdict',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='verdict',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='verdict',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='verdict',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='verdict',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='verdict',
            name='photo6',
        ),
        migrations.RemoveField(
            model_name='verdict',
            name='photo7',
        ),
        migrations.AddField(
            model_name='verdict',
            name='comment_from_user',
            field=models.CharField(default=1, max_length=9999, verbose_name='Комментарий пользователя'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VerdictPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='verdicts/photos', verbose_name='Фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('verdict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='webapp.verdict', verbose_name='Вердикт')),
            ],
            options={
                'verbose_name': 'Фотография вердикта',
                'verbose_name_plural': 'Фотографии вердикта',
            },
        ),
    ]
