# Generated by Django 5.2.3 on 2026-07-01 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_verdict_idempotency_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VkConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='VK peer ID')),
                ('from_id', models.BigIntegerField(db_index=True, verbose_name='VK user ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('avatar_url', models.URLField(blank=True, max_length=500, verbose_name='Аватар')),
                ('last_message_text', models.TextField(blank=True, verbose_name='Последнее сообщение')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('unread_count', models.PositiveIntegerField(default=0, verbose_name='Новые сообщения')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VK диалог',
                'verbose_name_plural': 'VK диалоги',
                'ordering': ('-last_message_at', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('user_agent', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Web Push подписка',
                'verbose_name_plural': 'Web Push подписки',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='VkMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_message_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('peer_id', models.BigIntegerField(db_index=True)),
                ('from_id', models.BigIntegerField(db_index=True)),
                ('direction', models.CharField(choices=[('incoming', 'Входящее'), ('outgoing', 'Исходящее')], max_length=16)),
                ('text', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('stored_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='webapp.vkconversation')),
            ],
            options={
                'verbose_name': 'VK сообщение',
                'verbose_name_plural': 'VK сообщения',
                'ordering': ('created_at', 'id'),
                'constraints': [models.UniqueConstraint(fields=('peer_id', 'vk_message_id', 'direction'), name='unique_vk_message_per_peer_direction')],
            },
        ),
    ]
