# Generated by Django 5.2 on 2025-05-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_verdict_photo1_remove_verdict_photo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verdict',
            name='brand',
            field=models.CharField(default=1, max_length=40, verbose_name='Бренд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verdict',
            name='item_model',
            field=models.CharField(default=1, max_length=40, verbose_name='Модель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verdict',
            name='status',
            field=models.CharField(choices=[('inpending', 'В обработке'), ('todo', 'Требует действия'), ('fake', 'Подделка'), ('legit', 'Оригинал'), ('dont_payment', 'Не оплачено')], default=1, max_length=20, verbose_name='Категория нарушения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verdict',
            name='category',
            field=models.CharField(choices=[('boots', 'Кроссовки'), ('pants', 'Штаны'), ('hoodie', 'Худи'), ('belt', 'Ремень'), ('bag', 'Сумка')], max_length=30, verbose_name='Категория вещи'),
        ),
    ]
