# Generated by Django 5.2 on 2025-05-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_verdict_brand_verdict_item_model_verdict_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verdict',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
