# Generated by Django 5.2.3 on 2026-07-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_vkconversation_webpushsubscription_vkmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verdictphoto',
            options={'ordering': ('id',), 'verbose_name': 'Фотография вердикта', 'verbose_name_plural': 'Фотографии вердикта'},
        ),
        migrations.AddIndex(
            model_name='emailotptoken',
            index=models.Index(fields=['email', 'used', '-created_at'], name='emailotp_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider_payment_id'], name='payment_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-date'], name='payment_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-date'], name='payment_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedverdictphoto',
            index=models.Index(fields=['user', 'verdict'], name='upload_user_verdict_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedverdictphoto',
            index=models.Index(fields=['user', '-created_at'], name='upload_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='verdict',
            index=models.Index(fields=['user', '-created_at'], name='verdict_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='verdict',
            index=models.Index(fields=['user', 'code'], name='verdict_user_code_idx'),
        ),
        migrations.AddIndex(
            model_name='verdict',
            index=models.Index(fields=['status', '-created_at'], name='verdict_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='verdictphoto',
            index=models.Index(fields=['verdict', 'id'], name='vphoto_verdict_id_idx'),
        ),
        migrations.AddIndex(
            model_name='vkconversation',
            index=models.Index(fields=['-last_message_at', '-updated_at'], name='vkconv_last_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='vkmessage',
            index=models.Index(fields=['conversation', '-created_at', '-id'], name='vkmsg_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='vkmessage',
            index=models.Index(fields=['peer_id', '-created_at'], name='vkmsg_peer_created_idx'),
        ),
        migrations.AddIndex(
            model_name='webpushsubscription',
            index=models.Index(fields=['active', '-updated_at'], name='webpush_active_updated_idx'),
        ),
    ]
